Search.appendIndex(
    [
                {
            "fqsen": "\\ApiMethods",
            "name": "ApiMethods",
            "summary": "",
            "url": "classes/ApiMethods.html"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/ApiMethods.html#method___construct"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AgenerateRandomChar\u0028\u0029",
            "name": "generateRandomChar",
            "summary": "Generate\u0020a\u0020random\u0020char\u0020with\u0020the\u0020variable\u0020\u0024chars",
            "url": "classes/ApiMethods.html#method_generateRandomChar"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AclearDB\u0028\u0029",
            "name": "clearDB",
            "summary": "Clean\u0020the\u0020db\u0020\u0028useful\u0020before\u0020tests\u0029",
            "url": "classes/ApiMethods.html#method_clearDB"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AgetLinks\u0028\u0029",
            "name": "getLinks",
            "summary": "Get\u0020the\u0020list\u0020of\u0020all\u0020links\u0020in\u0020the\u0020collection",
            "url": "classes/ApiMethods.html#method_getLinks"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AincrementCountHash\u0028\u0029",
            "name": "incrementCountHash",
            "summary": "Increment\u0020the\u0020count\u0020column\u0020in\u0020links\u0020collection",
            "url": "classes/ApiMethods.html#method_incrementCountHash"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AgetLongestHash\u0028\u0029",
            "name": "getLongestHash",
            "summary": "Function\u0020who\u0020permits\u0020to\u0020get\u0020the\u0020longest\u0020hash\u0020in\u0020collection",
            "url": "classes/ApiMethods.html#method_getLongestHash"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AhashExists\u0028\u0029",
            "name": "hashExists",
            "summary": "Function\u0020who\u0020return\u0020a\u0020document\u0020if\u0020the\u0020specified\u0020hash\u0020exists",
            "url": "classes/ApiMethods.html#method_hashExists"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AurlExists\u0028\u0029",
            "name": "urlExists",
            "summary": "Function\u0020who\u0020return\u0020a\u0020document\u0020if\u0020the\u0020specified\u0020url\u0020exists",
            "url": "classes/ApiMethods.html#method_urlExists"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AaddLinkToCollection\u0028\u0029",
            "name": "addLinkToCollection",
            "summary": "Function\u0020who\u0020add\u0020an\u0020url\u0020to\u0020the\u0020collection\nCheck\u0020that\u0020the\u0020url\u0020is\u0020correct\nCheck\u0020if\u0020it\u0020already\u0020exists\u0020and\u0020returns\u0020in\u0020this\u0020case\nAdd\u0020the\u0020url\u0020and\u0020generate\u0020an\u0020unique\u0020hash\u0020otherwise",
            "url": "classes/ApiMethods.html#method_addLinkToCollection"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AlogWiew\u0028\u0029",
            "name": "logWiew",
            "summary": "Function\u0020who\u0020log\u0020the\u0020visit\u0020of\u0020a\u0020redirected\u0020link",
            "url": "classes/ApiMethods.html#method_logWiew"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AgetHash\u0028\u0029",
            "name": "getHash",
            "summary": "Function\u0020who\u0020get\u0020an\u0020asked\u0020hash",
            "url": "classes/ApiMethods.html#method_getHash"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AgenerateUniqueString\u0028\u0029",
            "name": "generateUniqueString",
            "summary": "Function\u0020who\u0020generate\u0020an\u0020unique\u0020string\u0020into\u0020the\u0020collection\nUse\u0020the\u0020recursion\u0020to\u0020increase\u0020the\u0020size\u0020of\u0020the\u0020hash\u0020if\u0020the\u0020number\u0020of\u0020collisions\u0020exceeds\u0020\u0024maxAttempts",
            "url": "classes/ApiMethods.html#method_generateUniqueString"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AgetUndefinedError\u0028\u0029",
            "name": "getUndefinedError",
            "summary": "Generate\u0020a\u0020generic\u0020error",
            "url": "classes/ApiMethods.html#method_getUndefinedError"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AUNDEFINED_ERROR",
            "name": "UNDEFINED_ERROR",
            "summary": "Constants\u0020containing\u0020API\u0020messages\nUseful\u0020for\u0020debugging\u0020the\u0020API\u0020and\u0020precisely\u0020understanding\u0020what\u0020is\u0020wrong\u0020in\u0020case\u0020of\u0020a\u0020problem",
            "url": "classes/ApiMethods.html#constant_UNDEFINED_ERROR"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AINVALID_URL",
            "name": "INVALID_URL",
            "summary": "",
            "url": "classes/ApiMethods.html#constant_INVALID_URL"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AHASH_NOT_EXISTS",
            "name": "HASH_NOT_EXISTS",
            "summary": "",
            "url": "classes/ApiMethods.html#constant_HASH_NOT_EXISTS"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003ACREATE_ERROR",
            "name": "CREATE_ERROR",
            "summary": "",
            "url": "classes/ApiMethods.html#constant_CREATE_ERROR"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003AINCREMENT_COUNTER_ERROR",
            "name": "INCREMENT_COUNTER_ERROR",
            "summary": "",
            "url": "classes/ApiMethods.html#constant_INCREMENT_COUNTER_ERROR"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003A\u0024mongo",
            "name": "mongo",
            "summary": "",
            "url": "classes/ApiMethods.html#property_mongo"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003A\u0024result",
            "name": "result",
            "summary": "",
            "url": "classes/ApiMethods.html#property_result"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003A\u0024chars",
            "name": "chars",
            "summary": "",
            "url": "classes/ApiMethods.html#property_chars"
        },                {
            "fqsen": "\\ApiMethods\u003A\u003A\u0024maxAttempts",
            "name": "maxAttempts",
            "summary": "",
            "url": "classes/ApiMethods.html#property_maxAttempts"
        },                {
            "fqsen": "\\MongoDB",
            "name": "MongoDB",
            "summary": "",
            "url": "classes/MongoDB.html"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MongoDB.html#method___construct"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/MongoDB.html#method___destruct"
        },                {
            "fqsen": "\\MongoDB\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "",
            "url": "classes/MongoDB.html#method_getInstance"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "",
            "url": "classes/MongoDB.html#property_uri"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/MongoDB.html#property_client"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/MongoDB.html#property_db"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/MongoDB.html#property_instance"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024dbname",
            "name": "dbname",
            "summary": "",
            "url": "classes/MongoDB.html#property_dbname"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/MongoDB.html#property_username"
        },                {
            "fqsen": "\\MongoDB\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/MongoDB.html#property_password"
        },                {
            "fqsen": "\\ApiMethodsTest",
            "name": "ApiMethodsTest",
            "summary": "",
            "url": "classes/ApiMethodsTest.html"
        },                {
            "fqsen": "\\ApiMethodsTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/ApiMethodsTest.html#method_setUp"
        },                {
            "fqsen": "\\ApiMethodsTest\u003A\u003AtestAddLinkToCollection\u0028\u0029",
            "name": "testAddLinkToCollection",
            "summary": "",
            "url": "classes/ApiMethodsTest.html#method_testAddLinkToCollection"
        },                {
            "fqsen": "\\ApiMethodsTest\u003A\u003AtestGetHash\u0028\u0029",
            "name": "testGetHash",
            "summary": "",
            "url": "classes/ApiMethodsTest.html#method_testGetHash"
        },                {
            "fqsen": "\\ApiMethodsTest\u003A\u003AtestAddMultipleLinksToCollectionConcurrently\u0028\u0029",
            "name": "testAddMultipleLinksToCollectionConcurrently",
            "summary": "Add\u0020multiple\u0020links\u0020in\u0020parallel\u0020to\u0020test\u0020the\u0020load\u0020on\u0020the\u0020database",
            "url": "classes/ApiMethodsTest.html#method_testAddMultipleLinksToCollectionConcurrently"
        },                {
            "fqsen": "\\ApiMethodsTest\u003A\u003A\u0024api",
            "name": "api",
            "summary": "",
            "url": "classes/ApiMethodsTest.html#property_api"
        },                {
            "fqsen": "\\ApiMethodsTest\u003A\u003A\u0024concurrentInsert",
            "name": "concurrentInsert",
            "summary": "",
            "url": "classes/ApiMethodsTest.html#property_concurrentInsert"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
